PrimePark/urls.py
from django.contrib import admin
from django.urls import path, include

urlpatterns = [
    path('admin/', admin.site.urls),
 path('', include('home.urls')),
]

home/urls.py
from django.contrib import admin
from django.urls import path, include
from home import views
urlpatterns = [
    path('admin/', admin.site.urls),
    path('', views.home, name='home'),
    path('login/', views.login, name='login'),
    path('logout/', views.logout, name='logout'),
    path('signup/', views.signup, name='signup'),
    path('dashboard/', views.dashboard, name='dashboard'),
    path('createslot/', views.createslot, name='createslot'),
    path('table/', views.table, name='table'),

   
]

home/models.py
from importlib.abc import Traversable
import django
from django.contrib.auth.models import (AbstractBaseUser, AbstractUser,
                                      BaseUserManager)
from django.db import models


class UsersManager(BaseUserManager):
    def create_user(self, nid, password=None):
        if not nid:
            raise ValueError('Users must have an nid address')
        user = self.model(
            nid=self.normalize_email(nid),
        )
        user.set_password(password)
        user.save(using=self._db)
        return user
    
class Users(AbstractBaseUser):
    user_type = (
        ('R', 'Rentee'),
        ('S', 'Spot Owner'),
    )
    nid = models.CharField("nid",max_length=30, unique=True, primary_key=True)
    name = models.CharField("name",max_length=200)
    email = models.CharField("email",max_length=200)
    password = models.CharField("password",max_length=128)
    contact = models.CharField("contact",max_length=15, null=True)
    last_login = models.DateTimeField("last_login", auto_now_add=True, null=True)
    is_owner = models.CharField("is_owner", max_length=10, choices=user_type,default='user')
    USERNAME_FIELD = 'nid'
    objects = UsersManager()
    def __str__(self):
        return self.nid

class SpotOwner(models.Model):
    user = models.OneToOneField(Users, on_delete=models.CASCADE)
    balance = models.IntegerField(default=0)
    spot_ids = models.ManyToManyField('Spot', blank=True)

    def __str__(self):
        return self.user.nid


class Rentee(models.Model):
    user = models.OneToOneField(Users, on_delete=models.CASCADE)
    rentee_balance = models.IntegerField(default=0)
    rentee_spot_ids = models.ManyToManyField('Spot', blank=True)
    rentee_transactions = models.ManyToManyField('RenteeTransaction', blank=True)

    def __str__(self):
        return self.user.nid

class Drivers(models.Model):
    user = models.OneToOneField(Users, on_delete=models.CASCADE)
    driver_phone = models.IntegerField(default=0)
    driver_id = models.CharField("driver_id",max_length=30, unique=True, primary_key=True)
    
class Spot(models.Model):
    spot_id = models.CharField("spot_id",max_length=30, unique=True, primary_key=True)
    spot_name = models.CharField("spot_name",max_length=200)
    spot_road_no = models.CharField("spot_road_no",max_length=200)
    spot_area = models.CharField("spot_area",max_length=200)
    spot_house_no = models.CharField("spot_house_no",max_length=200)
    spot_city = models.CharField("spot_city",max_length=200)
    spot_owner = models.ForeignKey(Users, on_delete=models.CASCADE,null=True)
    spot_reviews = models.ManyToManyField('Review', blank=True)
    spot_timings = models.ManyToManyField('Timing', blank=True)
    spot_maps_url = models.CharField("spot_maps_url",max_length=200,null=True)
    spot_desc = models.CharField("spot_desc",max_length=200,null=True)
    spot_contact = models.CharField("spot_contact",max_length=200,null=True)
    def __str__(self):
        return self.spot_id
class Review(models.Model):
    review_id = models.CharField("review_id",max_length=30, unique=True, primary_key=True)
    review_text = models.CharField("review_text",max_length=200)
    review_rating = models.IntegerField("review_rating",default=0)
    review_date = models.DateTimeField("review_date", auto_now_add=True, null=True)
    review_user = models.ForeignKey(Users, on_delete=models.CASCADE)
    review_spot = models.ForeignKey(Spot, on_delete=models.CASCADE)
    def __str__(self):
        return self.review_id


class RenteeTransaction(models.Model):
    transaction_id = models.CharField("transaction_id",max_length=30, unique=True, primary_key=True)
    transaction_date = models.DateTimeField("transaction_date", auto_now_add=True, null=True)

class Timing(models.Model):
    timing_id = models.CharField("timing_id",max_length=30, unique=True, primary_key=True)
    timing_start = models.TimeField("timing_start")
    timing_end = models.TimeField("timing_end")
    timing_spot = models.ForeignKey(Spot, on_delete=models.CASCADE)
    def __str__(self):
        return self.timing_id

home/forms.py
import email
from django.forms import ModelForm
from .models import *
from django.contrib.auth.forms import UserCreationForm

class UserForm(ModelForm):
    class Meta: 
        model = Users
        fields = '__all__'

home/views.py
import re
from django.shortcuts import render,redirect
from django.contrib import messages
from django.http import HttpResponse
from django.contrib.auth import authenticate
from django.contrib.auth import login as login_user
from django.contrib.auth import logout as logout_user
from .forms import *
from .models import *
from pprint import pprint

# Create your views here.
def home(request):
    return render(request, 'home/dashboard.html')

def login(request):
    if request.method == 'POST':
        nid = request.POST.get('nid')
        password = request.POST.get('password')
        
        print(nid, password)
        
        
        user = authenticate(nid=nid, password=password)
        print("User:",user)
        if user is not None:
            login_user(request, user)
            return redirect('dashboard')
        else:
            messages.error(request, 'Invalid credentials')
            return redirect('login')
    else:
        return render(request, 'home/login.html')

def dashboard(request):
    if request.user.is_authenticated:
        print('Authenticated User:', request.user.nid)
        return render(request, 'home/dashboard.html')
    else:
        return HttpResponse('Unauthorized')

def createslot(request):
    print("CREATE SLOT")
    print(request.POST)
    if request.method == 'POST':
        print(request.POST)
    return render(request, 'home/createslot.html')

def signup(request):
    if request.method == 'POST':
        pprint(request.POST)
        user_name = request.POST.get('name')
        user_nid = request.POST.get('nid')
        user_email = request.POST.get('email')
        user_password = request.POST.get('password')
        user_contact = request.POST.get('contact')
        user_type = request.POST.get('is_owner')

        user = Users.objects.create(nid=user_nid, password=user_password, name=user_name, email=user_email, contact=user_contact, is_owner=user_type)
        user.save()
        messages.success(request, 'User created successfully')
        user.set_password(user_password)
        user.save()
        auth_user = authenticate(nid=user_nid, password=user_password)
        print("auth_user:",auth_user)
        return redirect('dashboard')
    else:
        return render(request, 'home/signup.html')



def logout(request):
    print('Logout User:', request.user.nid)
    logout_user(request)
    return redirect('login')

def table(request): 
    return render(request, 'home/table.html')

home/templates/home/createslot copy.html
{% extends 'base.html' %}

{% block title %}Create a Slot{% endblock title %}

{% block row1column1 %}

<div class="card">
    <div class="card-header"> <h4>
        Fill in Spot Information
    </h4></div> 
    <div class="card-body form-steps">
        <form action="" method="POST">
            {% csrf_token %}
            <div class="text-center pt-3 pb-4 mb-1">
                <!-- <img src="primepark.png" alt="" height=200px> -->
                <center>
                    <script src="https://unpkg.com/@lottiefiles/lottie-player@latest/dist/lottie-player.js"></script>
                    <lottie-player src="https://assets10.lottiefiles.com/packages/lf20_KLSxFl.json"  background="transparent"  speed="1"  style="width: 300px; height: 300px;"  loop  autoplay></lottie-player></center>
            </div>
            <div class="step-arrow-nav mb-4">

                <ul class="nav nav-pills custom-nav nav-justified" role="tablist">
                    <li class="nav-item" role="presentation">
                        <button class="nav-link done" id="steparrow-gen-info-tab" data-bs-toggle="pill" data-bs-target="#steparrow-gen-info" type="button" role="tab" aria-controls="steparrow-gen-info" aria-selected="true" data-position="0">General</button>
                    </li>
                    <li class="nav-item" role="presentation">
                        <button class="nav-link active" id="steparrow-description-info-tab" data-bs-toggle="pill" data-bs-target="#steparrow-description-info" type="button" role="tab" aria-controls="steparrow-description-info" aria-selected="false" data-position="1">Description</button>
                    </li>
                    <li class="nav-item" role="presentation">
                        <button class="nav-link" id="pills-experience-tab" data-bs-toggle="pill" data-bs-target="#pills-experience" type="button" role="tab" aria-controls="pills-experience" aria-selected="false" data-position="2">Finish</button>
                    </li>
                </ul>
            </div>

            <div class="tab-content">
                <div class="tab-pane fade" id="steparrow-gen-info" role="tabpanel" aria-labelledby="steparrow-gen-info-tab">
                    <div>
                        <div class="row">
                            <div class="col-lg-6">
                                <div class="mb-3">
                                    <label class="form-label" for="steparrow-gen-info-spotid-input">SpotID</label>
                                    <input type="text" class="form-control" id="steparrow-gen-info-spotid-input" required placeholder="Enter SpotID">
                                </div>
                            </div>
                            <div class="col-lg-6">
                                <div class="mb-3">
                                    <label class="form-label" for="steparrow-gen-info-area-input">Region/Area</label>
                                    <input type="text" class="form-control" id="steparrow-gen-info-area-input" required placeholder="Enter Area">
                                </div>
                            </div>
                        </div>
                        <div class="mb-3">
                            <label class="form-label" for="steparrow-gen-info-road-input">Road/Street</label>
                            <input type="text" class="form-control" id="steparrow-gen-info-road-input" required placeholder="Enter Road Number">
                        </div>
                        <div>
                            <label class="form-label" for="steparrow-gen-info-confirm-house-input">House/Plot</label>
                            <input type="text" class="form-control" id="steparrow-gen-info-confirm-house-input" required style="margin-bottom:15px" placeholder="Enter House Number">
                        </div>
                        <div>
                            <label class="form-label" for="steparrow-gen-info-contact-input">Contact Number</label>
                            <input type="number" class="form-control" id="steparrow-gen-info-contact-input" required placeholder="Enter Contact Number">
                        </div>
                    </div>
                    <div class="d-flex align-items-start gap-3 mt-4">
                        <button type="button" class="btn btn-success btn-label right ms-auto nexttab nexttab" data-nexttab="steparrow-description-info-tab"><i class="ri-arrow-right-line label-icon align-middle fs-16 ms-2" ></i>Next</button>
                    </div>  
                </div>
                <!-- end tab pane -->

                <div class="tab-pane fade show active" id="steparrow-description-info" role="tabpanel" aria-labelledby="steparrow-description-info-tab">
                    <div>
                        <div class="mb-3">
                            <label for="maps">Google Maps Link</label>
                            <input class="form-control" type="text" id="maps">
                        </div>
                        <div>
                            <label for="des-info-description-input">Description</label>
                            <textarea class="form-control" placeholder="Enter Extra Details" id="des-info-description-input" rows="3"></textarea>
                        </div>
                    </div>
                    <div class="d-flex align-items-start gap-3 mt-4">
                        <button type="button" class="btn btn-light btn-label previestab" data-previous="steparrow-gen-info-tab"><i class="ri-arrow-left-line label-icon align-middle fs-16 me-2"></i>Previous</button>
                        <button type="submit" class="btn btn-success btn-label right ms-auto nexttab nexttab" data-nexttab="pills-experience-tab"><i class="ri-arrow-right-line label-icon align-middle fs-16 ms-2"></i>Submit</button>
                    </div>
                </div>
                <!-- end tab pane -->

                <div class="tab-pane fade" id="pills-experience" role="tabpanel">
                    <div class="text-center">
                            
                        <div class="avatar-md mt-5 mb-4 mx-auto">
                            <div class="avatar-title bg-light text-success display-4 rounded-circle">
                                <i class="ri-checkbox-circle-fill"></i>
                            </div>
                        </div>
                        <h5>Thank You!</h5>
                        <p class="text-muted">You have Successfully Added a Spot</p>
                    </div>
                </div>
                <!-- end tab pane -->
            </div>
            <!-- end tab content -->
        </form>
    </div>
    <!-- end card body -->
</div>

{% endblock row1column1 %}

home/templates/home/createslot.html
{% extends 'base.html' %}
{% load static %}
{% block title %}Create a Slot{% endblock title %}

{% block row1column1 %}

<div class="card">
    <div class="card-header"> <h4>
        Fill in Spot Information
    </h4></div> 
    <div class="card-body form-steps">
        <form action="" method="POST">
            {% csrf_token %}
            <div class="text-center pt-3 pb-4 mb-1">
                <!-- <img src="primepark.png" alt="" height=200px> -->
            </div>
            <div class="step-arrow-nav mb-4">

                <ul class="nav nav-pills custom-nav nav-justified" role="tablist">
                    <li class="nav-item" role="presentation">
                        <button class="nav-link done" id="steparrow-gen-info-tab" data-bs-toggle="pill" data-bs-target="#steparrow-gen-info" type="button" role="tab" aria-controls="steparrow-gen-info" aria-selected="true" data-position="0">General</button>
                    </li>
                    <li class="nav-item" role="presentation">
                        <button class="nav-link active" id="steparrow-description-info-tab" data-bs-toggle="pill" data-bs-target="#steparrow-description-info" type="button" role="tab" aria-controls="steparrow-description-info" aria-selected="false" data-position="1">Description</button>
                    </li>
                    <li class="nav-item" role="presentation">
                        <button class="nav-link" id="pills-experience-tab" data-bs-toggle="pill" data-bs-target="#pills-experience" type="button" role="tab" aria-controls="pills-experience" aria-selected="false" data-position="2">Finish</button>
                    </li>
                </ul>
            </div>

            <div class="tab-content">
                <div class="tab-pane fade" id="steparrow-gen-info" role="tabpanel" aria-labelledby="steparrow-gen-info-tab">
                    <div>
                        <div class="row">
                            <div class="col-lg-6">
                                <div class="mb-3">
                                    <label name="spot_id" class="form-label" for="steparrow-gen-info-spotid-input">SpotID</label>
                                    <input name="spot_id"type="text" class="form-control" id="steparrow-gen-info-spotid-input" required placeholder="Enter SpotID">
                                </div>
                            </div>
                            <div class="col-lg-6">
                                <div class="mb-3">
                                    <label name="spot_area" class="form-label" for="steparrow-gen-info-area-input">Region/Area</label>
                                    <input name="spot_area" type="text" class="form-control" id="steparrow-gen-info-area-input" required placeholder="Enter Area">
                                </div>
                            </div>
                        </div>
                        <div class="mb-3">
                            <label name="spot_road" class="form-label" for="steparrow-gen-info-road-input">Road/Street</label>
                            <input name="spot_road" type="text" class="form-control" id="steparrow-gen-info-road-input" required placeholder="Enter Road Number">
                        </div>
                        <div>
                            <label name="spot_house"class="form-label" for="steparrow-gen-info-confirm-house-input">House/Plot</label>
                            <input type="text" class="form-control" id="steparrow-gen-info-confirm-house-input" required style="margin-bottom:15px" placeholder="Enter House Number">
                        </div>
                        <div>
                            <label name= "spot_number" class="form-label" for="steparrow-gen-info-contact-input">Contact Number</label>
                            <input name= "spot_number" type="number" class="form-control" id="steparrow-gen-info-contact-input" required placeholder="Enter Contact Number">
                        </div>
                    </div>
                    <div class="d-flex align-items-start gap-3 mt-4">
                        <button type="button" class="btn btn-success btn-label right ms-auto nexttab nexttab" data-nexttab="steparrow-description-info-tab"><i class="ri-arrow-right-line label-icon align-middle fs-16 ms-2" ></i>Next</button>
                    </div>  
                </div>
                <!-- end tab pane -->

                <div class="tab-pane fade show active" id="steparrow-description-info" role="tabpanel" aria-labelledby="steparrow-description-info-tab">
                    <div>
                        <div class="mb-3">
                            <label name="maps_url" for="maps">Google Maps Link</label>
                            <input name="maps_url" class="form-control" type="text" id="maps">
                        </div>
                        <div>
                            <label name="spot_desc" for="des-info-description-input">Description</label>
                            <textarea name="spot_desc" class="form-control" placeholder="Enter Extra Details" id="des-info-description-input" rows="3"></textarea>
                        </div>
                    </div>
                    <div class="d-flex align-items-start gap-3 mt-4">
                        <button type="button" class="btn btn-light btn-label previestab" data-previous="steparrow-gen-info-tab"><i class="ri-arrow-left-line label-icon align-middle fs-16 me-2"></i>Previous</button>
                        <button type="submit" class="btn btn-success btn-label right ms-auto nexttab nexttab" data-nexttab="pills-experience-tab"><i class="ri-arrow-right-line label-icon align-middle fs-16 ms-2"></i>Submit</button>
                    </div>
                </div>
                <!-- end tab pane -->

                <div class="tab-pane fade" id="pills-experience" role="tabpanel">
                    <div class="text-center">
                            
                        <div class="avatar-md mt-5 mb-4 mx-auto">
                            <div class="avatar-title bg-light text-success display-4 rounded-circle">
                                <i class="ri-checkbox-circle-fill"></i>
                            </div>
                        </div>
                        <h5>Thank You!</h5>
                        <p class="text-muted">You have Successfully Added a Spot</p>
                    </div>
                </div>
                <!-- end tab pane -->
            </div>
            <!-- end tab content -->
        </form>
    </div>
    <!-- end card body -->
</div>
{% endblock row1column1 %}

home/templates/home/dashboard.html
{% extends 'base.html' %}  
{% load static %}

{% block title %}Dashboard Page{% endblock title %}
{% block first_info %}
<div class="dropdown ms-sm-3 header-item topbar-user">
    <button type="button" class="btn" id="page-header-user-dropdown" data-bs-toggle="dropdown"
        aria-haspopup="true" aria-expanded="false">
        <span class="d-flex align-items-center">
            <img class="rounded-circle header-profile-user"
                src='{% static  "assets/images/users/avatar-1.jpg" %}' alt="Header Avatar">
            <span class="text-start ms-xl-2">
                <span class="d-none d-xl-inline-block ms-1 fw-medium user-name-text">{{request.user.name}}USER_FULL_NAME</span>
                <span
                    class="d-none d-xl-block ms-1 fs-12 text-muted user-name-sub-text">{{request.user.name}}USERNAME</span>
            </span>
        </span>
    </button>
    <div class="dropdown-menu dropdown-menu-end">
        <!-- item-->
        <h6 class="dropdown-header">Welcome {{USER_FULL_NAME}}!</h6>
        <a class="dropdown-item" href="pages-profile.html"><i
                class="mdi mdi-account-circle text-muted fs-16 align-middle me-1"></i> <span
                class="align-middle">Profile</span></a>
        
        <div class="dropdown-divider"></div>

        <a class="dropdown-item" href="{% url 'logout' %}"><i
                class="mdi mdi-logout text-muted fs-16 align-middle me-1"></i> <span
                class="align-middle" data-key="t-logout">Logout</span></a>
    </div>
</div>
{% endblock first_info %}

home/templates/home/home.html
{% load static %}
{% include 'base-sidebar.html' %}

home/templates/home/login.html
{% load static %}
<!DOCTYPE html>
<html lang="en">
<head>
    <meta charset="UTF-8">
    <meta http-equiv="X-UA-Compatible" content="IE=edge">
    <meta name="viewport" content="width=device-width, initial-scale=1.0">
    <link rel="stylesheet" href="https://unicons.iconscout.com/release/v4.0.0/css/line.css">
    <link rel="stylesheet" href="{% static 'assets/custom/style.css' %}">
         
</head>
<body>
    <div class="logo-img"></div>
    <div class="container">
        <div class="forms">
            <div class="form login">
                <span class="title">Login</span>
                {% if messages %}
                <ul class="messages">
                    {% for message in messages %}
                    <li {% if message.tags %} class=" {{ message.tags }} " {% endif %}> {{ message }} </li>
                    {% endfor %}
                </ul>
                {% endif %}
                <form action="" method="post">
                    {% csrf_token %}
                    <div class="input-field">
                        <input name="nid" id="nid_id" type="text" placeholder="Enter your NID" required>
                        <i class="uil uil-envelope icon"></i>
                    </div>
                    <div class="input-field">
                        <input name="password" id="password" type="password" class="password" placeholder="Enter your password" required>
                        <i class="uil uil-lock icon"></i>
                        <i class="uil uil-eye-slash showHidePw"></i>
                    </div>

                    <div class="checkbox-text">
                        <div class="checkbox-content">
                            <input type="checkbox" id="logCheck">
                            <label for="logCheck" class="text">Remember me</label>
                        </div>
                        
                        <a href="#" class="text">Forgot password?</a>
                    </div>

                    <div class="input-field button">
                        <input type="submit" value="Login">
                    </div>
                </form>

                <div class="login-signup">
                    <span class="text">Not a member?
                        <a href=" {% url 'signup' %}" class="text signup-link">Signup Now</a>
                    </span>
                </div>
            </div>

        </div>
    </div>

    <script src="{% static 'assets/custom/script.js' %}"></script>

</body>
</html>

home/templates/home/login2.html
{% load static %}
<!DOCTYPE html>
<html lang="en">
<head>
    <meta charset="UTF-8">
    <meta http-equiv="X-UA-Compatible" content="IE=edge">
    <meta name="viewport" content="width=device-width, initial-scale=1.0">
    <link rel="stylesheet" href="https://unicons.iconscout.com/release/v4.0.0/css/line.css">
    <link rel="stylesheet" href="{% static 'assets/custom/style.css' %}">
         
</head>
<body>
    <div class="logo-img"></div>
    <div class="container">
        <div class="forms">
            <div class="form login">
                <span class="title">Login</span>
                {% if messages %}
                <ul class="messages">
                    {% for message in messages %}
                    <li {% if message.tags %} class=" {{ message.tags }} " {% endif %}> {{ message }} </li>
                    {% endfor %}
                </ul>
                {% endif %}
                <form action="" method="post">
                    {% csrf_token %}
                    <div class="input-field">
                        <input name="nid" id="nid_id" type="text" placeholder="Enter your NID" required>
                        <i class="uil uil-envelope icon"></i>
                    </div>
                    <div class="input-field">
                        <input name="password" id="password" type="password" class="password" placeholder="Enter your password" required>
                        <i class="uil uil-lock icon"></i>
                        <i class="uil uil-eye-slash showHidePw"></i>
                    </div>

                    <div class="checkbox-text">
                        <div class="checkbox-content">
                            <input type="checkbox" id="logCheck">
                            <label for="logCheck" class="text">Remember me</label>
                        </div>
                        
                        <a href="#" class="text">Forgot password?</a>
                    </div>

                    <div class="input-field button">
                        <input type="submit" value="Login">
                    </div>
                </form>

                <div class="login-signup">
                    <span class="text">Not a member?
                        <a href=" {% url 'signup' %}" class="text signup-link">Signup Now</a>
                    </span>
                </div>
            </div>

        </div>
    </div>

    <script src="{% static 'assets/custom/script.js' %}"></script>

</body>
</html>

home/templates/home/signup.html
{% load static %}
<!DOCTYPE html>
<html lang="en">
<head>
    <meta charset="UTF-8">
    <meta http-equiv="X-UA-Compatible" content="IE=edge">
    <meta name="viewport" content="width=device-width, initial-scale=1.0">
    <link rel="stylesheet" href="https://unicons.iconscout.com/release/v4.0.0/css/line.css">
    <link rel="stylesheet" href="{% static 'assets/custom/style.css' %}">
         
</head>
<body>
    {% if messages %}
    <ul class="messages">
        {% for message in messages %}
        <li {% if message.tags %} class=" {{ message.tags }} " {% endif %}> {{ message }} </li>
        {% endfor %}
    </ul>
    {% endif %}
    <div class="logo-img"></div>
    <div class="container">
        <div class="forms">
            
            <div class="form signup">
                <span class="title">Registration</span>
                 
                {% if errors is not None %}
                {{ errors }}
                {% endif %}

                <form action="" method="post">
                    {% csrf_token %}
                    <div class="input-field">
                        <input name="name" type="text" placeholder="Enter your name" required>
                        <i class="uil uil-user"></i>
                    </div>
                    <div class="input-field">
                        <input name="nid" type="text" placeholder="Enter your NID" required>
                        <i class="uil uil-car"></i>
                    </div>
                    <div class="input-field">
                        <input name="email" type="text" placeholder="Enter your email" required>
                        <i class="uil uil-envelope icon"></i>
                    </div>
                    <div class="input-field">
                        <input name="phone" type="text" placeholder="Enter your phone number" required>
                        <i class="uil uil-phone icon"></i>
                    </div>
                    <div class="input-field">
                        <input name="password" type="password" class="password" placeholder="Create a password" required>
                        <i class="uil uil-lock icon"></i>
                        <i class="uil uil-eye-slash showHidePw"></i>
                    </div>

                    <div class="user-select">
                        <select name="is_owner" id="id_is_owner" for = "id_is_owner" required>
                          <option value="R">Select User Type:</option>
                          <option value="S">Spot Owner</option>
                          <option value="R">Spot Rentee</option>
                          <option value="D">Driver</option>
                        </select>
                    </div>

                    <div class="checkbox-text">
                        <div class="checkbox-content">
                            <input type="checkbox" id="termCon">
                            <label for="termCon" class="text">I accept all the terms and conditions</label>
                        </div>
                    </div>

                    <div class="input-field button">
                        <input type="submit" value="Signup">
                    </div>
                </form>

                <div class="login-signup">
                    <span class="text">Already a member?
                        <a href=" {% url 'login' %} " class="text login-link">Login Now</a>
                    </span>
                </div>
            </div>
        </div>
    </div>

    <script src="{% static 'assets/custom/script.js' %}"></script>

</body>
</html>

home/templates/home/test.html
<h2>{{form.valid}}</h2>
<form action="" method="post">
    {% csrf_token %}
    {{form.as_p}}
    <input type="submit" value="Submit">
</form>